- hosts: all
  tasks:
          - name: Adding docker repository
            yum_repository:
              name: docker
              description: docker YUM repo
              baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/

          - name: Installing Docker
            package:
                    name: docker-ce-18.06.3.ce-3.el7.x86_64
                    state: present

          - name: starting Docker services
            service:
                    name: docker
                    state: started
                    enabled: yes

          - name: installing pip3
            package:
                    name: python3-pip
                    state: present

          - name: Installing docker SDK for python
            command: pip3 install docker

          - name: changing iptables forward policy
            iptables:
                    chain: FORWARD
                    policy: ACCEPT

          - name: Pulling httpd image
            docker_image:
                    name: httpd
                    source: pull

          - name: making a directory
            file:
                    path: /home/myWebPage
                    state: directory
                    mode: '0755'

          - name: copying the files in the directory
            copy:
                    src: index.html
                    dest: /home/myWebPage

          - name: running a httpd container
            docker_container:
                    name: myweb
                    image: httpd
                    state: started
                    exposed_ports:
                    - "80"
                    ports:
                    - "8080:80"
                    volumes:
                    - /home/myWebPage:/usr/local/apache2/htdocs/
